language: go
sudo: false

matrix:
  include:
    - go: 1.5
    - go: 1.6
    - go: 1.7

branches:
  only:
    - v1

before_install:
  - go get golang.org/x/tools/cmd/cover

install:
  - mkdir -p $HOME/gopath/src/gopkg.in/anexia-it
  - mv $HOME/gopath/src/github.com/anexia-it/go-structmapper $HOME/gopath/src/gopkg.in/anexia-it/go-structmapper.v1
  - cd $HOME/gopath/src/gopkg.in/anexia-it/go-structmapper.v1

script:
  - go tool vet .
  - go test -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
