name: Code

on:
  push:
    branches:
      - main
  pull_request:

env:
  GO111MODULE: on

jobs:
  go-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - version: "1.16"
          name: target
        - version: "1.17"
          name: latest
    name: "Linting with ${{ matrix.go.name }} Go"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go.version }}
      - name: run linters
        run: |
          make go-lint
          make fmtcheck
