name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - version: "1.16"
          name: target
        - version: "1.17"
          name: latest
    name: "Unit tests with ${{ matrix.go.name }} Go"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go.version }}
      - name: run unit tests
        run: make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          files: ./coverage.out
          flags: unittests
          verbose: true
